# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f2fde3119e0f863ab9c4a9e475d5c9b541e68c5affc1aa868c0c0e46d0837daf568b9b5864ffc06381f3e5f91338c51e12bbbf71215be988977ec4235d8bf72

test:
  secret_key_base: deb8c21bb54a941691024bf03928fe73caf35abf44dfd173085ce6410aa5436483abc12af9fbb6edcc78d2d09b55f7b50c4a7cb10cefeae789a5689e4c024916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
